### ISSUE TITLE
Error analyzing file: Failed to fetch

### ISSUE THREAD

**Issue by shilojones** [statbid/shopping-feed-analyzer#2]
@DGuzmanRomano - we deployed this on a VM and I tried analyzing a file and here is what I received.  cc: @aalistarbid 

![image](https://github.com/user-attachments/assets/f0c77c68-e4c3-4686-a0df-6eed87017c0c)

**Comment by DGuzmanRomano** [comment]
Apologies for the missing README with instructions, I'll make sure to add that soon.

Regarding the error you're seeing, it usually occurs when the server isn't running. The React client appears to load fine so the issue is on the server side.

you have to start the react client:

Google-Shopping-Feed-Analyzer\client> npm start

then, from the server folder, start the server 

Google-Shopping-Feed-Analyzer\server> npm run dev

then you can refresh and start the analyzis

Also for the development environment, the server runs on port 3001. If that port isn't available on the VM, the application won't work.

Let me know if this helps or if you run into any other issues
